windows_x64_task:
  timeout_in: 90m
  windows_container:
    dockerfile: .ci/windows/Dockerfile

  build_vs32_script:
    - cmake -B build_win32 -G "Visual Studio 17 2022" -A "Win32"
    - cmake --build build_win32

  build_vs64_script:
    - cmake -B build_win64 -G "Visual Studio 17 2022" -A "x64"
    - cmake --build build_win64

  build_mingw32_script:
    - cmake -B build_mingw32 -G 'MSYS Makefiles'
    - cmake --build build_mingw32
  
  build_mingw64_script:
    - cmake -B build_mingw64 -G 'MSYS Makefiles'
    - cmake --build build_mingw64

  build_cygwin_script:
    - cmake -B build_cygwin -G 'Unix Makefiles'
    - cmake --build build_cygwin


linux_x64_task:
  container:
    dockerfile: .ci/linux_x64/Dockerfile

  build_script:
    - cmake -B build
    - cmake --build build